[project]
name = "tech-challenge-1609"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "y2kr", email = "nosh@tuta.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tech-challenge-1609 = "tech_challenge_1609:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
]
